// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using TomorrowsVoices.Data;

#nullable disable

namespace TomorrowsVoices.Data.TVMigrations
{
    [DbContext(typeof(TomorrowsVoicesContext))]
    [Migration("20250308171700_AddedScheduleonVOlunteer")]
    partial class AddedScheduleonVOlunteer
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "8.0.11");

            modelBuilder.Entity("TomorrowsVoices.Models.Attendance", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<bool>("IsArchived")
                        .HasColumnType("INTEGER");

                    b.Property<int>("SessionID")
                        .HasColumnType("INTEGER");

                    b.Property<int>("SingerID")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("Status")
                        .HasColumnType("INTEGER");

                    b.HasKey("ID");

                    b.HasIndex("SessionID");

                    b.HasIndex("SingerID");

                    b.ToTable("Attendances");
                });

            modelBuilder.Entity("TomorrowsVoices.Models.Director", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("TEXT");

                    b.Property<string>("FirstName")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("TEXT");

                    b.Property<bool>("IsArchived")
                        .HasColumnType("INTEGER");

                    b.Property<string>("LastName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.Property<int?>("LocationID")
                        .HasColumnType("INTEGER");

                    b.HasKey("ID");

                    b.HasIndex("Email")
                        .IsUnique();

                    b.ToTable("Directors");
                });

            modelBuilder.Entity("TomorrowsVoices.Models.Event", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<DateOnly>("Date")
                        .HasColumnType("TEXT");

                    b.Property<string>("Description")
                        .HasMaxLength(1000)
                        .HasColumnType("TEXT");

                    b.Property<TimeOnly>("EndTime")
                        .HasColumnType("TEXT");

                    b.Property<bool>("IsArchived")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("TEXT");

                    b.Property<string>("Notes")
                        .HasMaxLength(2000)
                        .HasColumnType("TEXT");

                    b.Property<TimeOnly>("StartTime")
                        .HasColumnType("TEXT");

                    b.Property<int>("VolLocationID")
                        .HasColumnType("INTEGER");

                    b.HasKey("ID");

                    b.HasIndex("VolLocationID");

                    b.ToTable("Events");
                });

            modelBuilder.Entity("TomorrowsVoices.Models.Location", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("City")
                        .HasColumnType("TEXT");

                    b.Property<int?>("DirectorID")
                        .HasColumnType("INTEGER");

                    b.HasKey("ID");

                    b.HasIndex("DirectorID")
                        .IsUnique();

                    b.ToTable("Locations");
                });

            modelBuilder.Entity("TomorrowsVoices.Models.Note", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("AttendanceID")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime?>("CreatedAt")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Description")
                        .HasColumnType("TEXT");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("TEXT");

                    b.HasKey("ID");

                    b.HasIndex("AttendanceID");

                    b.ToTable("Notes");
                });

            modelBuilder.Entity("TomorrowsVoices.Models.Schedule", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<bool>("IsArchived")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("IsPresent")
                        .HasColumnType("INTEGER");

                    b.Property<TimeOnly>("ShiftEnd")
                        .HasColumnType("TEXT");

                    b.Property<TimeOnly>("ShiftStart")
                        .HasColumnType("TEXT");

                    b.Property<int?>("VolLocationID")
                        .HasColumnType("INTEGER");

                    b.Property<int>("eventID")
                        .HasColumnType("INTEGER");

                    b.Property<int>("volunteerID")
                        .HasColumnType("INTEGER");

                    b.HasKey("ID");

                    b.HasIndex("VolLocationID");

                    b.HasIndex("eventID");

                    b.HasIndex("volunteerID");

                    b.ToTable("Schedules");
                });

            modelBuilder.Entity("TomorrowsVoices.Models.Session", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<DateTime?>("Date")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<bool>("IsArchived")
                        .HasColumnType("INTEGER");

                    b.Property<int?>("LocationID")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Notes")
                        .HasMaxLength(2000)
                        .HasColumnType("TEXT");

                    b.HasKey("ID");

                    b.HasIndex("LocationID");

                    b.ToTable("Sessions");
                });

            modelBuilder.Entity("TomorrowsVoices.Models.Singer", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("CreatedOn")
                        .HasColumnType("TEXT");

                    b.Property<string>("EmergencyContactName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.Property<string>("EmergencyContactNumber")
                        .IsRequired()
                        .HasMaxLength(10)
                        .HasColumnType("TEXT");

                    b.Property<string>("FirstName")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("TEXT");

                    b.Property<bool>("IsArchived")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("IsAvailable")
                        .HasColumnType("INTEGER");

                    b.Property<string>("LastName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.Property<int>("LocationID")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime?>("UpdatedOn")
                        .HasColumnType("TEXT");

                    b.HasKey("ID");

                    b.HasIndex("LocationID");

                    b.ToTable("Singers");
                });

            modelBuilder.Entity("TomorrowsVoices.Models.VolAttendance", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<TimeOnly?>("ActualEndTime")
                        .HasColumnType("TEXT");

                    b.Property<TimeOnly?>("ActualStartTime")
                        .HasColumnType("TEXT");

                    b.Property<DateOnly>("Date")
                        .HasColumnType("TEXT");

                    b.Property<int>("EventID")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("IsArchived")
                        .HasColumnType("INTEGER");

                    b.Property<TimeOnly>("ScheduledEndTime")
                        .HasColumnType("TEXT");

                    b.Property<TimeOnly>("ScheduledStartTime")
                        .HasColumnType("TEXT");

                    b.Property<bool>("Status")
                        .HasColumnType("INTEGER");

                    b.Property<int>("VolunteerID")
                        .HasColumnType("INTEGER");

                    b.HasKey("ID");

                    b.HasIndex("EventID");

                    b.HasIndex("VolunteerID");

                    b.ToTable("VolAttendances");
                });

            modelBuilder.Entity("TomorrowsVoices.Models.VolLocation", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("City")
                        .IsRequired()
                        .HasMaxLength(250)
                        .HasColumnType("TEXT");

                    b.Property<bool>("IsArchived")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Venue")
                        .HasColumnType("TEXT");

                    b.HasKey("ID");

                    b.ToTable("VolLocations");
                });

            modelBuilder.Entity("TomorrowsVoices.Models.Volunteer", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("TEXT");

                    b.Property<string>("FirstName")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("TEXT");

                    b.Property<bool>("IsArchived")
                        .HasColumnType("INTEGER");

                    b.Property<string>("LastName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.Property<string>("Phone")
                        .IsRequired()
                        .HasMaxLength(10)
                        .HasColumnType("TEXT");

                    b.Property<int>("VolLocationID")
                        .HasColumnType("INTEGER");

                    b.HasKey("ID");

                    b.HasIndex("VolLocationID");

                    b.ToTable("Volunteers");
                });

            modelBuilder.Entity("TomorrowsVoices.Models.Attendance", b =>
                {
                    b.HasOne("TomorrowsVoices.Models.Session", "Session")
                        .WithMany("Attendance")
                        .HasForeignKey("SessionID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("TomorrowsVoices.Models.Singer", "Singer")
                        .WithMany("Attendance")
                        .HasForeignKey("SingerID")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Session");

                    b.Navigation("Singer");
                });

            modelBuilder.Entity("TomorrowsVoices.Models.Event", b =>
                {
                    b.HasOne("TomorrowsVoices.Models.VolLocation", "VolLocation")
                        .WithMany("Events")
                        .HasForeignKey("VolLocationID")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("VolLocation");
                });

            modelBuilder.Entity("TomorrowsVoices.Models.Location", b =>
                {
                    b.HasOne("TomorrowsVoices.Models.Director", "Director")
                        .WithOne("Location")
                        .HasForeignKey("TomorrowsVoices.Models.Location", "DirectorID")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.Navigation("Director");
                });

            modelBuilder.Entity("TomorrowsVoices.Models.Note", b =>
                {
                    b.HasOne("TomorrowsVoices.Models.Attendance", "Attendance")
                        .WithMany()
                        .HasForeignKey("AttendanceID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Attendance");
                });

            modelBuilder.Entity("TomorrowsVoices.Models.Schedule", b =>
                {
                    b.HasOne("TomorrowsVoices.Models.VolLocation", null)
                        .WithMany("Schedules")
                        .HasForeignKey("VolLocationID");

                    b.HasOne("TomorrowsVoices.Models.Event", "Event")
                        .WithMany("Schedules")
                        .HasForeignKey("eventID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("TomorrowsVoices.Models.Volunteer", "Volunteer")
                        .WithMany("Schedules")
                        .HasForeignKey("volunteerID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Event");

                    b.Navigation("Volunteer");
                });

            modelBuilder.Entity("TomorrowsVoices.Models.Session", b =>
                {
                    b.HasOne("TomorrowsVoices.Models.Location", "Location")
                        .WithMany("Session")
                        .HasForeignKey("LocationID")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.Navigation("Location");
                });

            modelBuilder.Entity("TomorrowsVoices.Models.Singer", b =>
                {
                    b.HasOne("TomorrowsVoices.Models.Location", "Location")
                        .WithMany("Singer")
                        .HasForeignKey("LocationID")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Location");
                });

            modelBuilder.Entity("TomorrowsVoices.Models.VolAttendance", b =>
                {
                    b.HasOne("TomorrowsVoices.Models.Event", "Event")
                        .WithMany("VolAttendance")
                        .HasForeignKey("EventID")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("TomorrowsVoices.Models.Volunteer", "Volunteer")
                        .WithMany("VolAttendances")
                        .HasForeignKey("VolunteerID")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Event");

                    b.Navigation("Volunteer");
                });

            modelBuilder.Entity("TomorrowsVoices.Models.Volunteer", b =>
                {
                    b.HasOne("TomorrowsVoices.Models.VolLocation", "VolLocation")
                        .WithMany("Volunteers")
                        .HasForeignKey("VolLocationID")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("VolLocation");
                });

            modelBuilder.Entity("TomorrowsVoices.Models.Director", b =>
                {
                    b.Navigation("Location");
                });

            modelBuilder.Entity("TomorrowsVoices.Models.Event", b =>
                {
                    b.Navigation("Schedules");

                    b.Navigation("VolAttendance");
                });

            modelBuilder.Entity("TomorrowsVoices.Models.Location", b =>
                {
                    b.Navigation("Session");

                    b.Navigation("Singer");
                });

            modelBuilder.Entity("TomorrowsVoices.Models.Session", b =>
                {
                    b.Navigation("Attendance");
                });

            modelBuilder.Entity("TomorrowsVoices.Models.Singer", b =>
                {
                    b.Navigation("Attendance");
                });

            modelBuilder.Entity("TomorrowsVoices.Models.VolLocation", b =>
                {
                    b.Navigation("Events");

                    b.Navigation("Schedules");

                    b.Navigation("Volunteers");
                });

            modelBuilder.Entity("TomorrowsVoices.Models.Volunteer", b =>
                {
                    b.Navigation("Schedules");

                    b.Navigation("VolAttendances");
                });
#pragma warning restore 612, 618
        }
    }
}
