// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using TomorrowsVoices.Data;

#nullable disable

namespace TomorrowsVoices.Data.TVMigrations
{
    [DbContext(typeof(TomorrowsVoicesContext))]
    [Migration("20250123215239_deleted database")]
    partial class deleteddatabase
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "8.0.11");

            modelBuilder.Entity("TomorrowsVoices.Models.Attendance", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("SessionID")
                        .HasColumnType("INTEGER");

                    b.Property<int>("SingerID")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("Status")
                        .HasColumnType("INTEGER");

                    b.HasKey("ID");

                    b.HasIndex("SessionID");

                    b.HasIndex("SingerID");

                    b.ToTable("Attendances");
                });

            modelBuilder.Entity("TomorrowsVoices.Models.Director", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Email")
                        .HasMaxLength(255)
                        .HasColumnType("TEXT");

                    b.Property<string>("FirstName")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("TEXT");

                    b.Property<string>("LastName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.HasKey("ID");

                    b.HasIndex("Email")
                        .IsUnique();

                    b.ToTable("Directors");
                });

            modelBuilder.Entity("TomorrowsVoices.Models.Location", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("City")
                        .HasColumnType("INTEGER");

                    b.Property<int>("DirectorID")
                        .HasColumnType("INTEGER");

                    b.HasKey("ID");

                    b.HasIndex("DirectorID")
                        .IsUnique();

                    b.ToTable("Locations");
                });

            modelBuilder.Entity("TomorrowsVoices.Models.Note", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("AttendanceID")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime?>("CreatedAt")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Description")
                        .HasColumnType("TEXT");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("TEXT");

                    b.HasKey("ID");

                    b.HasIndex("AttendanceID");

                    b.ToTable("Notes");
                });

            modelBuilder.Entity("TomorrowsVoices.Models.Session", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<DateTime?>("Date")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("LocationID")
                        .HasColumnType("INTEGER");

                    b.HasKey("ID");

                    b.HasIndex("LocationID");

                    b.ToTable("Sessions");
                });

            modelBuilder.Entity("TomorrowsVoices.Models.Singer", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int?>("DirectorID")
                        .HasColumnType("INTEGER");

                    b.Property<string>("FirstName")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("TEXT");

                    b.Property<string>("LastName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.Property<int>("LocationID")
                        .HasColumnType("INTEGER");

                    b.HasKey("ID");

                    b.HasIndex("DirectorID");

                    b.HasIndex("LocationID");

                    b.ToTable("Singers");
                });

            modelBuilder.Entity("TomorrowsVoices.Models.Attendance", b =>
                {
                    b.HasOne("TomorrowsVoices.Models.Session", "Session")
                        .WithMany("Attendance")
                        .HasForeignKey("SessionID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("TomorrowsVoices.Models.Singer", "Singer")
                        .WithMany("Attendance")
                        .HasForeignKey("SingerID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Session");

                    b.Navigation("Singer");
                });

            modelBuilder.Entity("TomorrowsVoices.Models.Location", b =>
                {
                    b.HasOne("TomorrowsVoices.Models.Director", "Director")
                        .WithOne("Location")
                        .HasForeignKey("TomorrowsVoices.Models.Location", "DirectorID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Director");
                });

            modelBuilder.Entity("TomorrowsVoices.Models.Note", b =>
                {
                    b.HasOne("TomorrowsVoices.Models.Attendance", "Attendance")
                        .WithMany()
                        .HasForeignKey("AttendanceID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Attendance");
                });

            modelBuilder.Entity("TomorrowsVoices.Models.Session", b =>
                {
                    b.HasOne("TomorrowsVoices.Models.Location", "Location")
                        .WithMany("Session")
                        .HasForeignKey("LocationID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Location");
                });

            modelBuilder.Entity("TomorrowsVoices.Models.Singer", b =>
                {
                    b.HasOne("TomorrowsVoices.Models.Director", null)
                        .WithMany("Singer")
                        .HasForeignKey("DirectorID");

                    b.HasOne("TomorrowsVoices.Models.Location", "Location")
                        .WithMany("Singer")
                        .HasForeignKey("LocationID")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Location");
                });

            modelBuilder.Entity("TomorrowsVoices.Models.Director", b =>
                {
                    b.Navigation("Location");

                    b.Navigation("Singer");
                });

            modelBuilder.Entity("TomorrowsVoices.Models.Location", b =>
                {
                    b.Navigation("Session");

                    b.Navigation("Singer");
                });

            modelBuilder.Entity("TomorrowsVoices.Models.Session", b =>
                {
                    b.Navigation("Attendance");
                });

            modelBuilder.Entity("TomorrowsVoices.Models.Singer", b =>
                {
                    b.Navigation("Attendance");
                });
#pragma warning restore 612, 618
        }
    }
}
