using System.ComponentModel.DataAnnotations;

namespace TomorrowsVoices.Models
{
    public enum City
    {
        [Display(Name = "Abbotsford")]
        Abbotsford = 1,
        [Display(Name = "Ajax")]
        Ajax = 2,
        [Display(Name = "Airdrie")]
        Airdrie = 3,
        [Display(Name = "Barrie")]
        Barrie = 4,
        [Display(Name = "Belleville")]
        Belleville = 5,
        [Display(Name = "Blainville")]
        Blainville = 6,
        [Display(Name = "Brandon")]
        Brandon = 7,
        [Display(Name = "Brantford")]
        Brantford = 8,
        [Display(Name = "Brossard")]
        Brossard = 9,
        [Display(Name = "Burnaby")]
        Burnaby = 10,
        [Display(Name = "Burlington")]
        Burlington = 11,
        [Display(Name = "Calgary")]
        Calgary = 12,
        [Display(Name = "Cambridge")]
        Cambridge = 13,
        [Display(Name = "Cape Breton")]
        CapeBreton = 14,
        [Display(Name = "Charlottetown")]
        Charlottetown = 15,
        [Display(Name = "Chatham-Kent")]
        ChathamKent = 16,
        [Display(Name = "Chilliwack")]
        Chilliwack = 17,
        [Display(Name = "Coquitlam")]
        Coquitlam = 18,
        [Display(Name = "Corner Brook")]
        CornerBrook = 19,
        [Display(Name = "Delta")]
        Delta = 20,
        [Display(Name = "Dieppe")]
        Dieppe = 21,
        [Display(Name = "Dollard-des-Ormeaux")]
        DollardDesOrmeaux = 22,
        [Display(Name = "Drummondville")]
        Drummondville = 23,
        [Display(Name = "Edmonton")]
        Edmonton = 24,
        [Display(Name = "Fort McMurray")]
        FortMcMurray = 25,
        [Display(Name = "Fredericton")]
        Fredericton = 26,
        [Display(Name = "Gatineau")]
        Gatineau = 27,
        [Display(Name = "Grande Prairie")]
        GrandePrairie = 28,
        [Display(Name = "Guelph")]
        Guelph = 29,
        [Display(Name = "Halifax")]
        Halifax = 30,
        [Display(Name = "Hamilton")]
        Hamilton = 31,
        [Display(Name = "Kamloops")]
        Kamloops = 32,
        [Display(Name = "Kelowna")]
        Kelowna = 33,
        [Display(Name = "Kingston")]
        Kingston = 34,
        [Display(Name = "Kitchener")]
        Kitchener = 35,
        [Display(Name = "Langley")]
        Langley = 36,
        [Display(Name = "Laval")]
        Laval = 37,
        [Display(Name = "Lethbridge")]
        Lethbridge = 38,
        [Display(Name = "Levis")]
        Levis = 39,
        [Display(Name = "Lloydminster")]
        Lloydminster = 40,
        [Display(Name = "London")]
        London = 41,
        [Display(Name = "Longueuil")]
        Longueuil = 42,
        [Display(Name = "Maple Ridge")]
        MapleRidge = 43,
        [Display(Name = "Markham")]
        Markham = 44,
        [Display(Name = "Medicine Hat")]
        MedicineHat = 45,
        [Display(Name = "Milton")]
        Milton = 46,
        [Display(Name = "Mirabel")]
        Mirabel = 47,
        [Display(Name = "Moncton")]
        Moncton = 48,
        [Display(Name = "Montreal")]
        Montreal = 49,
        [Display(Name = "Moose Jaw")]
        MooseJaw = 50,
        [Display(Name = "Nanaimo")]
        Nanaimo = 51,
        [Display(Name = "Newmarket")]
        Newmarket = 52,
        [Display(Name = "New Westminster")]
        NewWestminster = 53,
        [Display(Name = "Niagara")]
        Niagara = 54,
        [Display(Name = "North Bay")]
        NorthBay = 55,
        [Display(Name = "North Vancouver")]
        NorthVancouver = 56,
        [Display(Name = "Oakville")]
        Oakville = 57,
        [Display(Name = "Oshawa")]
        Oshawa = 58,
        [Display(Name = "Orillia")]
        Orillia = 59,
        [Display(Name = "Ottawa")]
        Ottawa = 60,
        [Display(Name = "Peterborough")]
        Peterborough = 61,
        [Display(Name = "Pickering")]
        Pickering = 62,
        [Display(Name = "Prince Albert")]
        PrinceAlbert = 63,
        [Display(Name = "Prince George")]
        PrinceGeorge = 64,
        [Display(Name = "Quebec City")]
        QuebecCity = 65,
        [Display(Name = "Red Deer")]
        RedDeer = 66,
        [Display(Name = "Regina")]
        Regina = 67,
        [Display(Name = "Repentigny")]
        Repentigny = 68,
        [Display(Name = "Richmond")]
        Richmond = 69,
        [Display(Name = "Richmond Hill")]
        RichmondHill = 70,
        [Display(Name = "Saanich")]
        Saanich = 71,
        [Display(Name = "Saint-Jean-sur-Richelieu")]
        SaintJeanSurRichelieu = 72,
        [Display(Name = "Saint-Jérôme")]
        SaintJerome = 73,
        [Display(Name = "Saint John")]
        SaintJohn = 74,
        [Display(Name = "St. Albert")]
        StAlbert = 75,
        [Display(Name = "St. Catharines")]
        StCatharines = 76,
        [Display(Name = "St. John's")]
        StJohns = 77,
        [Display(Name = "Sarnia")]
        Sarnia = 78,
        [Display(Name = "Sault Ste. Marie")]
        SaultSteMarie = 79,
        [Display(Name = "Saskatoon")]
        Saskatoon = 80,
        [Display(Name = "Shawinigan")]
        Shawinigan = 81,
        [Display(Name = "Sherbrooke")]
        Sherbrooke = 82,
        [Display(Name = "Spruce Grove")]
        SpruceGrove = 83,
        [Display(Name = "Strathcona County")]
        StrathconaCounty = 84,
        [Display(Name = "Sudbury")]
        Sudbury = 85,
        [Display(Name = "Surrey")]
        Surrey = 86,
        [Display(Name = "Terrebonne")]
        Terrebonne = 87,
        [Display(Name = "Thunder Bay")]
        ThunderBay = 88,
        [Display(Name = "Toronto")]
        Toronto = 89,
        [Display(Name = "Trois-Rivières")]
        TroisRivieres = 90,
        [Display(Name = "Vancouver")]
        Vancouver = 91,
        [Display(Name = "Vaughan")]
        Vaughan = 92,
        [Display(Name = "Victoria")]
        Victoria = 93,
        [Display(Name = "Waterloo")]
        Waterloo = 94,
        [Display(Name = "Welland")]
        Welland = 95,
        [Display(Name = "Whitehorse")]
        Whitehorse = 96,
        [Display(Name = "Whitby")]
        Whitby = 97,
        [Display(Name = "Windsor")]
        Windsor = 98,
        [Display(Name = "Winnipeg")]
        Winnipeg = 99,
        [Display(Name = "Wood Buffalo")]
        WoodBuffalo = 100,
        [Display(Name = "Yellowknife")]
        Yellowknife = 101
    }
}
