using System.ComponentModel.DataAnnotations;

namespace TomorrowsVoices.Models
{
    public enum City
    {
        Toronto = 1,
        Saskatoon = 2,
        Niagara = 3,
        Vancouver = 4,
        Hamilton = 5,
        Surrey = 6,
        [Display(Name = "St. Catharines")]
        StCatharines = 7,
        Montreal = 8,
        Calgary = 9,
        Edmonton = 10,
        Ottawa = 11,
        Winnipeg = 12,
        [Display(Name = "Quebec City")]
        QuebecCity = 13,
        Kitchener = 14,
        London = 15,
        Victoria = 16,
        Halifax = 17,
        Oshawa = 18,
        Windsor = 19,
        Regina = 20,
        Markham = 21,
        Vaughan = 22,
        Gatineau = 23,
        Burnaby = 24,
        Laval = 25,
        Richmond = 26,
        [Display(Name = "Richmond Hill")]
        RichmondHill = 27,
        Oakville = 28,
        Burlington = 29,
        Barrie = 30,
        Abbotsford = 31,
        Coquitlam = 32,
        Sherbrooke = 33,
        Kelowna = 34,
        Cambridge = 35,
        Kingston = 36,
        Guelph = 37,
        Waterloo = 38,
        Brantford = 39,
        Pickering = 40,
        Ajax = 41,
        Milton = 42,
        Whitby = 43,
        [Display(Name = "Thunder Bay")]
        ThunderBay = 44,
        [Display(Name = "Chatham-Kent")]
        ChathamKent = 45,
        [Display(Name = "Red Deer")]
        RedDeer = 46,
        Lethbridge = 47,
        Saanich = 48,
        Delta = 49,
        Kamloops = 50,
        Nanaimo = 51,
        [Display(Name = "Saint John")]
        SaintJohn = 52,
        Moncton = 53,
        Fredericton = 54,
        [Display(Name = "Cape Breton")]
        CapeBreton = 55,
        Chilliwack = 56,
        [Display(Name = "Maple Ridge")]
        MapleRidge = 57,
        [Display(Name = "North Vancouver")]
        NorthVancouver = 58,
        Newmarket = 59,
        Peterborough = 60,
        Sarnia = 61,
        Belleville = 62,
        [Display(Name = "Fort McMurray")]
        FortMcMurray = 63,
        [Display(Name = "Grande Prairie")]
        GrandePrairie = 64,
        [Display(Name = "Medicine Hat")]
        MedicineHat = 65,
        Airdrie = 66,
        [Display(Name = "St. Albert")]
        StAlbert = 67,
        [Display(Name = "Spruce Grove")]
        SpruceGrove = 68,
        Lloydminster = 69,
        [Display(Name = "Prince George")]
        PrinceGeorge = 70,
        [Display(Name = "Sault Ste. Marie")]
        SaultSteMarie = 71,
        Sudbury = 72,
        [Display(Name = "Trois-Rivières")]
        TroisRivieres = 73,
        Terrebonne = 74,
        [Display(Name = "Saint-Jérôme")]
        SaintJerome = 75,
        Drummondville = 76,
        [Display(Name = "Saint-Jean-sur-Richelieu")]
        SaintJeanSurRichelieu = 77,
        Repentigny = 78,
        Brossard = 79,
        Longueuil = 80,
        Levis = 81,
        Blainville = 82,
        Mirabel = 83,
        Shawinigan = 84,
        [Display(Name = "Dollard-des-Ormeaux")]
        DollardDesOrmeaux = 85,
        Dieppe = 86,
        Charlottetown = 87,
        Whitehorse = 88,
        Yellowknife = 89,
        [Display(Name = "St. John's")]
        StJohns = 90,
        [Display(Name = "Corner Brook")]
        CornerBrook = 91,
        Brandon = 92,
        [Display(Name = "Moose Jaw")]
        MooseJaw = 93,
        [Display(Name = "Prince Albert")]
        PrinceAlbert = 94,
        [Display(Name = "North Bay")]
        NorthBay = 95,
        Orillia = 96,
        [Display(Name = "Wood Buffalo")]
        WoodBuffalo = 97,
        [Display(Name = "Strathcona County")]
        StrathconaCounty = 98,
        Langley = 99,
        [Display(Name = "New Westminster")]
        NewWestminster = 100,
        Welland = 101
    }
}